project:
  type: website
  output-dir: docs


render:
      - index.qmd
      - 10-API-INTRO.qmd
      - 11-API-OPENDATASOFT.qmd
      - 12-API-exo.qmd
      - 13-API-CARTO.qmd
      - 21-CARTO-ParisPC.qmd
      - 22-CARTO-mapsf.qmd
      - 23-CARTO-leaflet.qmd
      - 31-PROJET-data.qmd
      - 32-PROJET-shiny.qmd
      
website:
  sidebar:
    search: true
    contents:
      - section: "API"
        contents:
          - 10-API-INTRO.qmd
          - 11-API-OPENDATASOFT.qmd
          - 12-API-exo.qmd  
      - section: "CARTO"
        contents:
          - 13-API-CARTO.qmd
          - 21-CARTO-ParisPC.qmd
          - 22-CARTO-mapsf.qmd
          - 23-CARTO-leaflet.qmd
      - section: "PROJET"
        contents:
          - 31-PROJET-data.qmd
          - 32-PROJET-shiny.qmd


 
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



