project:
  type: website
  output-dir: docs


render:
      - index.qmd
      - 10-API-INTRO.qmd
      - 11-API-OPENDATASOFT.qmd
      - 12-API-exo.qmd

website:
  sidebar:
    search: true
    contents:
      - section: "API"
        contents:
          - 10-API-INTRO.qmd
          - 11-API-OPENDATASOFT.qmd
          - 12-API-exo.qmd          
      - section: "CARTO"



 
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



