project:
  type: website
  output-dir: docs


render:
      - index.qmd
      - 10-API-INTRO.qmd
      - 11-API-OPENDATASOFT.qmd


website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "API"
        contents:
          - 10-API-INTRO.qmd
          - 11-API-OPENDATASOFT.qmd
      - section: "Layout"



 
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



